### ISSUE TITLE
EITDATA file is corrupted

### ISSUE THREAD

**Issue by fsmMLK** [EIT-team/Stroke_EIT_Dataset#6]
Please verify EITDATA.json file. It is corrupted and does not contain all data.

**Comment by rkalahasty** [comment]
Did you find a work around?

**Comment by fsmMLK** [comment]
Yes, I used the matlab files.

**Comment by Jimbles** [comment]
Hey! Thanks for the reminder of this, and the interest in the data. MATLAB writing JSON has a character limit so the JSON was truncated. This has been fixed in resfix #7
